# Generated by Django 2.1.1 on 2018-09-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_cadastro_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='celular',
            field=models.PositiveIntegerField(verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='endereco',
            field=models.CharField(max_length=255, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome '),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.PositiveIntegerField(verbose_name='Tel.Fixo'),
        ),
    ]
