# Generated by Django 2.1.1 on 2018-09-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20180928_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
